name: LBDG
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40551
title: Welcome to the Future
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2c373e'
    - '#ffffff'
    - '#b3650e'
    - '#97998e'
  brandStrength: 0.625
  lightness: 0.9586575333960354
  saturation: 0.35121046169660985
  rhythmicContrast: 0.3573941288050264
purpose: []
