name: LBDG
favicon: null
layout_spectrum: 0.76244
typography_spectrum: 0.40551
title: The Online Home of JL Civi
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#486186'
    - '#d6dfde'
    - '#b07949'
    - '#b1c1da'
    - '#7e95b4'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
